local logger = require("logger")
require("table_util")
local StackReplayTestingUtils = require("tests.StackReplayTestingUtils")
local testReplayFolder = "tests/replays/"

-- Endless
local match, _ = StackReplayTestingUtils:simulateReplayWithPath(testReplayFolder .. "v046-2023-01-30-00-35-24-Spd1-Dif3-endless.txt")
assert(match ~= nil)
assert(match.mode == "endless")
assert(match.seed == 7161965)
assert(match.P1.game_over_clock == 402)
assert(match.P1.max_health == 1)
assert(match.P1.score == 37)
assert(match.P1.difficulty == 3)

-- Time Attack
match, _ = StackReplayTestingUtils:simulateReplayWithPath(testReplayFolder .. "v046-2022-09-12-04-02-30-Spd11-Dif1-timeattack.txt")
assert(match ~= nil)
assert(match.mode == "time")
assert(match.seed == 3490465)
assert(match.P1.game_stopwatch == 7201)
assert(match.P1.max_health == 1)
assert(match.P1.score == 10353)
assert(match.P1.difficulty == 1)
assert(table.length(match.P1.chains) == 8)
assert(table.length(match.P1.combos) == 0)

-- Vs
match, _ = StackReplayTestingUtils:simulateReplayWithPath(testReplayFolder .. "v046-2023-01-28-02-39-32-JamBox-L10-vs-Galadic97-L10-Casual-P1wins.txt")
assert(match ~= nil)
assert(match.mode == "vs")
assert(match.seed == 2992240)
assert(match.P1.game_over_clock == 2039)
assert(match.P1.level == 10)
assert(table.length(match.P1.chains) == 4)
assert(table.length(match.P1.combos) == 4)
assert(match.P2.game_over_clock == 0)
assert(match.P2.level == 10)
assert(table.length(match.P2.chains) == 4)
assert(table.length(match.P2.combos) == 4)
